### ISSUE TITLE
catch i2cReadOnce error

### ISSUE THREAD

**Issue by farfromrefug** [nebrius/raspi-io-core#1]
I can't find a way to catch ```i2cReadOnce``` errors.
When the device is not connected i get an ```EIO, Input/output error``` error.
I thus tried to surround it with a try/catch but it does not seem to work( because the error is thrown inside the [read](https://github.com/nebrius/raspi-io-core/blob/master/src/index.js#L693) method?
Could you make it so that we can catch that error.
I actualy think this is very important (especially when the device can be plugged or not).

Thanks

**Comment by nebrius** [comment]
Hi @farfromrefug! My apologies, the notification for this issue slipped through the cracks in my email. The full I2C read path is synchronous, so you should be able to catch the exception. Can you show a code snippet to give some more context?

**Comment by farfromrefug** [comment]
@nebrius No problem! I was using raspi through ```johnn-five```. I don't have an sample code anymore as i had to drop raspi and johnny-five all together.
But looking through my commit logs, what i can tell you is that i was doing something like ```board.io.i2cReadOnce(...)``` within a Promise and the error was apparently not thrown.
I am sorry it's been quite sometimes and i rewrote almost all of my code :s

Thanks

**Comment by nebrius** [comment]
Ah, yes, promises swallow errors in JavaScript (unless you wrap the callback in a setTimeout). Instead of using try/catch statements, you would need to use the `.catch()` method in the promise chain.

I'm going to go ahead and close this issue, but feel free to reopen if you decide to revisit using Johnny Five!
